//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_tours
    {
        public book_tours()
        {
            this.orders = new HashSet<order>();
        }
    
        public long id { get; set; }
        public long tour_id { get; set; }
        public long customer_id { get; set; }
        public int quantity { get; set; }
        public System.DateTime booking_date { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public bool status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual tour tour { get; set; }
        public virtual ICollection<order> orders { get; set; }
    }
}
