//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietkhachsantour
    {
        public long makhachsan { get; set; }
        public long matour { get; set; }
        public string vitriphong { get; set; }
        public long succhua { get; set; }
    
        public virtual khachsan khachsan { get; set; }
        public virtual tour tour { get; set; }
    }
}
