//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class chucvu
    {
        public chucvu()
        {
            this.nhanviens = new HashSet<nhanvien>();
        }
    
        public long id { get; set; }
        public string tenchucvu { get; set; }
        public double hesoluong { get; set; }
    
        public virtual ICollection<nhanvien> nhanviens { get; set; }
    }
}
