//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class chuongtrinhtour
    {
        public chuongtrinhtour()
        {
            this.khachsantheochuongtrinhs = new HashSet<khachsantheochuongtrinh>();
            this.phancongnhanviens = new HashSet<phancongnhanvien>();
            this.phuongtientheochuongtrinhs = new HashSet<phuongtientheochuongtrinh>();
        }
    
        public long id { get; set; }
        public string tieude { get; set; }
        public System.DateTime thoigianbatdau { get; set; }
        public System.DateTime thoigianketthuc { get; set; }
        public string mota { get; set; }
        public long tour_id { get; set; }
    
        public virtual tour tour { get; set; }
        public virtual ICollection<khachsantheochuongtrinh> khachsantheochuongtrinhs { get; set; }
        public virtual ICollection<phancongnhanvien> phancongnhanviens { get; set; }
        public virtual ICollection<phuongtientheochuongtrinh> phuongtientheochuongtrinhs { get; set; }
    }
}
