//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.book_tours = new HashSet<book_tours>();
            this.orders = new HashSet<order>();
            this.ratings = new HashSet<rating>();
        }
    
        public long id { get; set; }
        public string full_name { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string image { get; set; }
        public string address { get; set; }
        public long user_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<book_tours> book_tours { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<rating> ratings { get; set; }
    }
}
