//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class diachi
    {
        public long id { get; set; }
        public string xa { get; set; }
        public string huyen { get; set; }
        public string tinh { get; set; }
        public string ghichu { get; set; }
        public long khachhang_id { get; set; }
    
        public virtual khachhang khachhang { get; set; }
    }
}
