//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadon
    {
        public int mahoadon { get; set; }
        public string trangthaithanhtoan { get; set; }
        public string phuongthucthanhtoan { get; set; }
        public string masothue { get; set; }
        public string tendonvi { get; set; }
        public string diachidonvi { get; set; }
        public string nguoidaidien { get; set; }
        public Nullable<long> maphieuhuytour { get; set; }
        public long maphieudattour { get; set; }
        public int is_delete { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public double tongsotien { get; set; }
    
        public virtual phieudattour phieudattour { get; set; }
        public virtual phieuhuytour phieuhuytour { get; set; }
    }
}
