//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadon
    {
        public hoadon()
        {
            this.phieuhuytours = new HashSet<phieuhuytour>();
        }
    
        public long id { get; set; }
        public decimal tongsotien { get; set; }
        public string trangthai { get; set; }
        public string phuongthucthanhtoan { get; set; }
        public long khachhang_id { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
    
        public virtual khachhang khachhang { get; set; }
        public virtual ICollection<phieuhuytour> phieuhuytours { get; set; }
    }
}
