//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachsan
    {
        public khachsan()
        {
            this.khachsantheochuongtrinhs = new HashSet<khachsantheochuongtrinh>();
        }
    
        public long id { get; set; }
        public string tenkhachsan { get; set; }
        public string diachi { get; set; }
        public string sodienthoai { get; set; }
        public string chatluong { get; set; }
    
        public virtual ICollection<khachsantheochuongtrinh> khachsantheochuongtrinhs { get; set; }
    }
}
