//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachsantheochuongtrinh
    {
        public long khachsan_id { get; set; }
        public long chuongtrinhtour_id { get; set; }
        public string vitri { get; set; }
        public long succhua { get; set; }
    
        public virtual chuongtrinhtour chuongtrinhtour { get; set; }
        public virtual khachsan khachsan { get; set; }
    }
}
