//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachsan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khachsan()
        {
            this.chitietkhachsantours = new HashSet<chitietkhachsantour>();
        }
    
        public long makhachsan { get; set; }
        public string tenkhachsan { get; set; }
        public string diachi { get; set; }
        public string sodienthoai { get; set; }
        public string chatluong { get; set; }
        public double giakhachsan { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietkhachsantour> chitietkhachsantours { get; set; }
    }
}
