//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class loaikhachhang
    {
        public loaikhachhang()
        {
            this.khachhangs = new HashSet<khachhang>();
        }
    
        public long maloaikhachhang { get; set; }
        public string tenloaikhachhang { get; set; }
        public int mucapdunggia { get; set; }
    
        public virtual ICollection<khachhang> khachhangs { get; set; }
    }
}
