//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        public nhanvien()
        {
            this.phancongnhanviens = new HashSet<phancongnhanvien>();
            this.chucvus = new HashSet<chucvu>();
        }
    
        public long id { get; set; }
        public string hoten { get; set; }
        public string gioitinh { get; set; }
        public System.DateTime ngaysinh { get; set; }
        public string sodienthoai { get; set; }
        public string email { get; set; }
        public string bangcap { get; set; }
        public string hinhdaidien { get; set; }
        public long luong { get; set; }
        public System.DateTime ngayvaolam { get; set; }
        public long phongban_id { get; set; }
    
        public virtual phongban phongban { get; set; }
        public virtual ICollection<phancongnhanvien> phancongnhanviens { get; set; }
        public virtual ICollection<chucvu> chucvus { get; set; }
    }
}
