//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhomquyen
    {
        public nhomquyen()
        {
            this.quyen_nhomquyen = new HashSet<quyen_nhomquyen>();
            this.users = new HashSet<user>();
        }
    
        public long manhomquyen { get; set; }
        public string tennhomquyen { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<quyen_nhomquyen> quyen_nhomquyen { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
