//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieuhuytour
    {
        public long id { get; set; }
        public decimal sotienhoan { get; set; }
        public string lydohuy { get; set; }
        public long hoadon_id { get; set; }
        public Nullable<System.DateTime> ngayhuy { get; set; }
    
        public virtual hoadon hoadon { get; set; }
    }
}
