//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ql_tourdulich_ptudtmEntities : DbContext
    {
        public ql_tourdulich_ptudtmEntities()
            : base("name=ql_tourdulich_ptudtmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<backup_schedules> backup_schedules { get; set; }
        public virtual DbSet<blogtour> blogtours { get; set; }
        public virtual DbSet<chitietkhachsantour> chitietkhachsantours { get; set; }
        public virtual DbSet<chitietphieudattour> chitietphieudattours { get; set; }
        public virtual DbSet<chitietphuongtientour> chitietphuongtientours { get; set; }
        public virtual DbSet<chitiettour> chitiettours { get; set; }
        public virtual DbSet<chucvu> chucvus { get; set; }
        public virtual DbSet<chuongtrinhtour> chuongtrinhtours { get; set; }
        public virtual DbSet<danhgia> danhgias { get; set; }
        public virtual DbSet<diemdulich> diemduliches { get; set; }
        public virtual DbSet<failed_jobs> failed_jobs { get; set; }
        public virtual DbSet<footer_grid_ones> footer_grid_ones { get; set; }
        public virtual DbSet<footer_grid_threes> footer_grid_threes { get; set; }
        public virtual DbSet<footer_grid_twos> footer_grid_twos { get; set; }
        public virtual DbSet<footer_socials> footer_socials { get; set; }
        public virtual DbSet<footer_titles> footer_titles { get; set; }
        public virtual DbSet<hinhanhtour> hinhanhtours { get; set; }
        public virtual DbSet<hoadon> hoadons { get; set; }
        public virtual DbSet<khachhang> khachhangs { get; set; }
        public virtual DbSet<khachsan> khachsans { get; set; }
        public virtual DbSet<khuyenmai> khuyenmais { get; set; }
        public virtual DbSet<loaiblog> loaiblogs { get; set; }
        public virtual DbSet<loaikhachhang> loaikhachhangs { get; set; }
        public virtual DbSet<loaitour> loaitours { get; set; }
        public virtual DbSet<migration> migrations { get; set; }
        public virtual DbSet<nhanvien> nhanviens { get; set; }
        public virtual DbSet<nhomquyen> nhomquyens { get; set; }
        public virtual DbSet<password_reset_tokens> password_reset_tokens { get; set; }
        public virtual DbSet<personal_access_tokens> personal_access_tokens { get; set; }
        public virtual DbSet<phancongchucvu> phancongchucvus { get; set; }
        public virtual DbSet<phancongnhanvien> phancongnhanviens { get; set; }
        public virtual DbSet<phieudattour> phieudattours { get; set; }
        public virtual DbSet<phieuhuytour> phieuhuytours { get; set; }
        public virtual DbSet<phongban> phongbans { get; set; }
        public virtual DbSet<phuongtien> phuongtiens { get; set; }
        public virtual DbSet<quyen> quyens { get; set; }
        public virtual DbSet<quyen_nhomquyen> quyen_nhomquyen { get; set; }
        public virtual DbSet<tour> tours { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
