//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ql_tourdulichEntities : DbContext
    {
        public ql_tourdulichEntities()
            : base("name=ql_tourdulichEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<blogtour> blogtours { get; set; }
        public DbSet<chitiettour> chitiettours { get; set; }
        public DbSet<chucvu> chucvus { get; set; }
        public DbSet<chuongtrinhtour> chuongtrinhtours { get; set; }
        public DbSet<danhgia> danhgias { get; set; }
        public DbSet<dattour> dattours { get; set; }
        public DbSet<diachi> diachis { get; set; }
        public DbSet<diemdulich> diemduliches { get; set; }
        public DbSet<failed_jobs> failed_jobs { get; set; }
        public DbSet<hinhanhtour> hinhanhtours { get; set; }
        public DbSet<hoadon> hoadons { get; set; }
        public DbSet<khachhang> khachhangs { get; set; }
        public DbSet<khachsan> khachsans { get; set; }
        public DbSet<khachsantheochuongtrinh> khachsantheochuongtrinhs { get; set; }
        public DbSet<khuyenmai> khuyenmais { get; set; }
        public DbSet<loaiblog> loaiblogs { get; set; }
        public DbSet<loaitour> loaitours { get; set; }
        public DbSet<migration> migrations { get; set; }
        public DbSet<nhanvien> nhanviens { get; set; }
        public DbSet<nhomquyen> nhomquyens { get; set; }
        public DbSet<password_reset_tokens> password_reset_tokens { get; set; }
        public DbSet<personal_access_tokens> personal_access_tokens { get; set; }
        public DbSet<phancongnhanvien> phancongnhanviens { get; set; }
        public DbSet<phieuhuytour> phieuhuytours { get; set; }
        public DbSet<phongban> phongbans { get; set; }
        public DbSet<phuongtien> phuongtiens { get; set; }
        public DbSet<phuongtientheochuongtrinh> phuongtientheochuongtrinhs { get; set; }
        public DbSet<tour> tours { get; set; }
        public DbSet<user> users { get; set; }
    }
}
