//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour_schedules
    {
        public tour_schedules()
        {
            this.schedules_hotels = new HashSet<schedules_hotels>();
            this.schedules_transports = new HashSet<schedules_transports>();
            this.tour_guides = new HashSet<tour_guides>();
        }
    
        public long id { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> time_in_date { get; set; }
        public string description { get; set; }
        public long tour_detail_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<schedules_hotels> schedules_hotels { get; set; }
        public virtual ICollection<schedules_transports> schedules_transports { get; set; }
        public virtual tour_details tour_details { get; set; }
        public virtual ICollection<tour_guides> tour_guides { get; set; }
    }
}
