//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.khachhangs = new HashSet<khachhang>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> email_verified_at { get; set; }
        public string password { get; set; }
        public System.DateTime create_at { get; set; }
        public string status { get; set; }
        public string remember_token { get; set; }
        public long nhomquyen_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<khachhang> khachhangs { get; set; }
        public virtual nhomquyen nhomquyen { get; set; }
    }
}
